### ISSUE TITLE
java.lang.ClassNotFoundException: com.aruistar.cordova.baidumap.BaiduMapLocation

### ISSUE THREAD

**Issue by gogo123150** [aruis/cordova-plugin-baidumaplocation#51]
android

W/System.err: java.lang.ClassNotFoundException: com.aruistar.cordova.baidumap.BaiduMapLocation
                  at java.lang.Class.classForName(Native Method)
W/System.err:     at java.lang.Class.forName(Class.java:400)
                  at java.lang.Class.forName(Class.java:326)

**Comment by gogo123150** [comment]
在plugin.xml文件中
查找“app/” 替换为空

**Comment by gogo123150** [comment]
并手动将app目录移到libs及src目录下
