### ISSUE TITLE
ionic3上使用这个插件一直无法定位

### ISSUE THREAD

**Issue by gdongy** [aruis/cordova-plugin-baidumaplocation#59]
在ionic3上插件没反应，然后找到你说的临时解决办法，
把platforms下边的app文件下的libs下的文件都拿过去放到app下边的libs之后打包会报错，就只把jar包放过去了，同时也把src下的文件也放到APP下边的src文件下边，打包不报错了，但是就是获取不到定位信息，一直报你说的是key的问题的情况；
我反复检查了信息，检查了key，也检查了创建应用的时候的包名和shal，是没问题的；我在想是不是和libs下边的文件有关系，但是不知道该怎么改，麻烦楼主帮看看，谢谢

**Comment by gdongy** [comment]
loctype 162,百度开发中心上说是so配置问题，我按照你给的方法试过了还不行，有点郁闷了

**Comment by garyganyang** [comment]
我也用不了, 闪退  Android 8, ionic 3

2018-11-23 14:36:02.031 10578-10578/com.ssy.lipo:core D/AndroidRuntime: Shutting down VM
2018-11-23 14:36:02.033 10578-10578/com.ssy.lipo:core E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ssy.lipo:core, PID: 10578
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ssy.lipo-sD5iCgUxIY_7Lr2ECLcTRA==/base.apk"],nativeLibraryDirectories=[/data/app/com.ssy.lipo-sD5iCgUxIY_7Lr2ECLcTRA==/lib/arm64, /data/app/com.ssy.lipo-sD5iCgUxIY_7Lr2ECLcTRA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libAliFaceAREngine.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.lipo.hello.MainApplication.loadLibs(MainApplication.java:131)
        at com.lipo.hello.MainApplication.onCreate(MainApplication.java:77)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5879)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6699)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
2018-11-23 14:36:02.039 3889-4231/? D/PowerKeeper.Event: notifyAMCrash packageName: 0, pid:10578
2018-11-23 14:36:02.039 1370-14210/? W/ActivityManager: Process com.ssy.lipo has crashed too many times: killing!

**Comment by gdongy** [comment]
> 我也用不了, 闪退 Android 8, ionic 3
> 
> 2018-11-23 14:36:02.031 10578-10578/com.ssy.lipo:core D/AndroidRuntime: Shutting down VM
> 2018-11-23 14:36:02.033 10578-10578/com.ssy.lipo:core E/AndroidRuntime: FATAL EXCEPTION: main
> Process: com.ssy.lipo:core, PID: 10578
> java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ssy.lipo-sD5iCgUxIY_7Lr2ECLcTRA==/base.apk"],nativeLibraryDirectories=[/data/app/com.ssy.lipo-sD5iCgUxIY_7Lr2ECLcTRA==/lib/arm64, /data/app/com.ssy.lipo-sD5iCgUxIY_7Lr2ECLcTRA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libAliFaceAREngine.so"
> at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
> at java.lang.System.loadLibrary(System.java:1657)
> at com.lipo.hello.MainApplication.loadLibs(MainApplication.java:131)
> at com.lipo.hello.MainApplication.onCreate(MainApplication.java:77)
> at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
> at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5879)
> at android.app.ActivityThread.-wrap1(Unknown Source:0)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
> at android.os.Handler.dispatchMessage(Handler.java:105)
> at android.os.Looper.loop(Looper.java:171)
> at android.app.ActivityThread.main(ActivityThread.java:6699)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
> 2018-11-23 14:36:02.039 3889-4231/? D/PowerKeeper.Event: notifyAMCrash packageName: 0, pid:10578
> 2018-11-23 14:36:02.039 1370-14210/? W/ActivityManager: Process com.ssy.lipo has crashed too many times: killing!

解决了吗
