### ISSUE TITLE
安卓调用getCurrentPosition无响应

### ISSUE THREAD

**Issue by Dongsipan** [aruis/cordova-plugin-baidumaplocation#83]
V/Capacitor/Plugin: To native (Cordova plugin): callbackId: BaiduMapLocation874731680, service: BaiduMapLocation, action: getCurrentPosition, actionArgs: [null]
W/System.err: java.lang.ClassNotFoundException: com.aruistar.cordova.baidumap.BaiduMapLocation
W/System.err:     at java.lang.Class.classForName(Native Method)
W/System.err:     at java.lang.Class.forName(Class.java:454)
W/System.err:     at java.lang.Class.forName(Class.java:379)
W/System.err:     at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
W/System.err:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
W/System.err:     at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:70)
W/System.err:     at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:46)
W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err:     at android.os.Looper.loop(Looper.java:178)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)
W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.aruistar.cordova.baidumap.BaiduMapLocation" on path: DexPathList[[zip file "/data/app/io.ionic.starter-CwpssdsMTslrxMZzEz7ZcA==/base.apk"],nativeLibraryDirectories=[/data/app/io.ionic.starter-CwpssdsMTslrxMZzEz7ZcA==/lib/arm64, /system/lib64, /system/product/lib64]]
W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:230)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/System.err: 	... 12 more
I/System.out: Error adding plugin com.aruistar.cordova.baidumap.BaiduMapLocation.

**Comment by chary2060** [comment]
<source-file src="src/android/BaiduMapLocation.java" target-dir="app/src/com/aruistar/cordova/baidumap"/>
改成        <source-file src="src/android/BaiduMapLocation.java" target-dir="src/com/aruistar/cordova/baidumap"/>

**Comment by chary2060** [comment]
<source-file src="src/android/BaiduMapLocation.java" target-dir="app/src/com/aruistar/cordova/baidumap"/>
改成
        <source-file src="src/android/BaiduMapLocation.java" target-dir="src/com/aruistar/cordova/baidumap"/>

**Comment by chary2060** [comment]
<source-file src="src/android/BaiduMapLocation.java" target-dir="src/com/aruistar/cordova/baidumap"/>

**Comment by lylovexm** [comment]
请问这个解决了吗?  android7.1版本

**Comment by chary2060** [comment]
> 请问这个解决了吗? android7.1版本

plugin.xml  中的BaiduMapLocation路径写错了，target-dir去掉app/
<source-file src="src/android/BaiduMapLocation.java" target-dir="src/com/aruistar/cordova/baidumap" />

**Comment by LningCode** [comment]
我也是在安卓上面没有回调，去掉app/y也不行

**Comment by chary2060** [comment]
> 我也是在安卓上面没有回调，去掉app/y也不行

那我就不知道了，platform >android  自行调试吧。。。

**Comment by LningCode** [comment]
兄弟我的ios和安卓都没有反应，一会有出现什么code&nbsp;no&nbsp;net，还后面就没有了，能加个微信或者qq请教一下不


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chen.zhipeng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月5日(星期四) 下午5:33
收件人:&nbsp;"aruis/cordova-plugin-baidumaplocation"<cordova-plugin-baidumaplocation@noreply.github.com&gt;;
抄送:&nbsp;"林福宁"<1170096634@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [aruis/cordova-plugin-baidumaplocation] 安卓调用getCurrentPosition无响应 (#83)



 
我也是在安卓上面没有回调，去掉app/y也不行
  
那我就不知道了，platform &gt;android &nbsp;自行调试吧。。。

**Comment by chary2060** [comment]
> 兄弟我的ios和安卓都没有反应，一会有出现什么code&nbsp;no&nbsp;net，还后面就没有了，能加个微信或者qq请教一下不
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"chen.zhipeng"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月5日(星期四) 下午5:33 收件人:&nbsp;"aruis/cordova-plugin-baidumaplocation"<cordova-plugin-baidumaplocation@noreply.github.com&gt;; 抄送:&nbsp;"林福宁"<1170096634@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [aruis/cordova-plugin-baidumaplocation] 安卓调用getCurrentPosition无响应 (#83) 我也是在安卓上面没有回调，去掉app/y也不行 那我就不知道了，platform &gt;android &nbsp;自行调试吧。。。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

qq1319915051
